//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Medicine
    {
        public System.Guid medicine_id { get; set; }
        public string medicine_name { get; set; }
        public System.Guid health_id { get; set; }
        public int medicine_quantity { get; set; }
    
        public virtual Health Health { get; set; }
    }
}
