//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PetAPI.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Treat
    {
        public System.Guid treat_id { get; set; }
        public string treat_name { get; set; }
        public System.Guid pet_type_id { get; set; }
        public System.Guid hunger_id { get; set; }
        public int treat_quantity { get; set; }
        public int calories { get; set; }
    
        public virtual Hunger Hunger { get; set; }
        public virtual Pet_Type Pet_Type { get; set; }
    }
}
